<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="style.css"/>
	<title>Vélos en réparation</title>
	</head>
	<script type="text/javascript" src="../JS/MesFonctionsJS.js"></script>

    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>


	<body >

	
	<form method="post" action="">
	<table>
		<tr>
		
			<td>Identifiant</td>
		
		</tr>
		<?php 
		require_once '../Controller/VeloController.php';

		$velos = ModelVelo::getVelosRep(); 
		foreach ($velos as $velo):?>
		<tr>
			<td style="text-align:center"id="unVelo"> <?php echo $velo->getIdVelo()?> </td>
			<td> <input type="button" value="Details" onclick="detailVelo($('#unVelo').val())">  </td>  
		</tr>
		<?php endforeach;?>
	</table>	
	</form>
	
	<div id='details'></div>

	<footer>
			
			<ul id="footer-menu">
				<li>
				<b>Intranet Vélo'v ©</b>
				</li>
			</ul>
		
	</footer>
		
	</body>
</html>